# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-08 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_tweets', to='users.User'),
        ),
    ]
